import React from "react";
import Image from "next/image";
import SectionTitle from "@/components/section-title";
import ContactForm from "./components/contact-form";
import contactImage from "@/public/images/contact-page.jpg";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact Page | Galere Template",
  description: "Generated by simbanic software services",
};

const ContactFormLayout = () => {
  return (
    <div className="flex flex-wrap justify-between max-w-[1320px] mx-auto my-10 px-3 lg:px-0">
      <div className="w-full md:w-1/2 p-8 bg-white shadow-md">
        <SectionTitle
          title="CONTACT US"
          subtitle="Let's Start Working!"
          titleClass="text-[18px] text-gray-600 text-left font-semibold"
          subtitleClass="text-[35px] text-left font-medium font-montAlt"
        />

        <ContactForm />
      </div>
      <div className="w-full md:w-1/2">
        <Image
          src={contactImage}
          alt="Contact Us"
          width={600}
          height={600}
          className="object-cover h-full w-full"
        />
      </div>
    </div>
  );
};

export default ContactFormLayout;
