import type { Metadata } from "next";
import { Montserrat_Alternates, Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/theme-context";
import { ToastProvider } from "@/context/toast-context";

const fontRoboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-roboto",
});
const montserratAlternates = Montserrat_Alternates({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat-alternates",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Galere Template",
  description: "Generated by simbanic software services",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontRoboto.variable} ${montserratAlternates.variable} font-sans`}
      >
        <ToastProvider>
          <ThemeProvider>{children} </ThemeProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
