import SectionTitle from "@/components/section-title";
import Image from "next/image";
import React from "react";
import aboutImage from "@/public/images/about-page.jpg";
import StatsSection from "./components/stats-component";
import ServicesSection from "./components/service-component";
import { detailsText } from "./data/section-detail-text";
import DetailsText from "./components/section-detail-text-component";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Page | Galere Template",
  description: "Generated by simbanic software services",
};

const AboutPage = () => {
  return (
    <>
      <div className="flex flex-col lg:flex-row justify-between max-w-[1320px] mx-auto my-10">
        <div className="w-full lg:w-1/2 p-8 ">
          <SectionTitle
            title="ABOUT US"
            subtitle="Ten Years Fulfilling Dreams"
            titleClass="text-[18px] text-gray-600 text-left font-semibold dark:text-gray-300"
            subtitleClass="text-[35px] text-left font-medium font-montAlt dark:text-gray-200"
          />
          <DetailsText text={detailsText} />
        </div>
        <div className="w-full lg:w-1/2 p-8 ">
          <Image
            src={aboutImage}
            alt="about Us"
            width={600}
            height={600}
            className="object-cover h-full w-full rounded-lg"
          />
        </div>
      </div>
      <StatsSection />
      <ServicesSection />
    </>
  );
};

export default AboutPage;
